# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-13 16:26
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('base', '0018_auto_20161113_1611'),
    ]

    operations = [
        migrations.AddField(
            model_name='n_notificationtype',
            name='body_format',
            field=models.TextField(default='', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='n_notificationtype',
            name='title_format',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notification',
            name='create_at',
            field=models.DateField(auto_now_add=True, default=datetime.datetime(2016, 11, 13, 16, 26, 8, 112251)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='create_at',
            field=models.DateField(default=datetime.datetime(2016, 11, 13, 16, 24, 48, 155943)),
        ),
        migrations.AlterField(
            model_name='order',
            name='due_date',
            field=models.DateField(default=datetime.datetime(2016, 11, 13, 16, 24, 48, 156078)),
        ),
    ]
