# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-30 18:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StripeCustomer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripeid', models.CharField(max_length=50)),
                ('stripetoken', models.CharField(max_length=50)),
            ],
        ),
    ]
