# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2016-11-23 21:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('address', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comments', models.CharField(blank=True, max_length=50)),
                ('background', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Links',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField()),
                ('description', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('image', models.FileField(upload_to='')),
                ('gallery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business_site.Gallery')),
            ],
        ),
        migrations.CreateModel(
            name='Website',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.FileField(blank=True, upload_to='')),
                ('description', models.CharField(max_length=50)),
                ('publish', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='links',
            name='website',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='business_site.Website'),
        ),
        migrations.AddField(
            model_name='gallery',
            name='website',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='business_site.Website'),
        ),
        migrations.AddField(
            model_name='contactus',
            name='website',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='business_site.Website'),
        ),
    ]
