# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-01 20:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('business_site', '0004_auto_20161201_1532'),
    ]

    operations = [
        migrations.AddField(
            model_name='basicinfo',
            name='website',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE,
                                       to='business_site.Website'),
        ),
    ]
