# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-10 20:23
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('base', '0005_auto_20161109_1539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='create_at',
            field=models.DateField(default=datetime.datetime(2016, 11, 10, 20, 23, 54, 246638)),
        ),
        migrations.AlterField(
            model_name='order',
            name='due_date',
            field=models.DateField(default=datetime.datetime(2016, 11, 10, 20, 23, 54, 246671)),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='create_at',
            field=models.DateField(auto_now_add=True),
        ),
    ]
