# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-02 04:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('stripe_cater', '0006_auto_20161202_0413'),
    ]

    operations = [
        migrations.CreateModel(
            name='Charge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=6)),
                ('captured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('captured_at', models.DateTimeField(null=True)),
                ('status', models.CharField(default='PENDING', max_length=10)),
            ],
        ),
        migrations.RenameModel(
            old_name='Payment',
            new_name='PaymentOrder',
        ),
        migrations.AddField(
            model_name='charge',
            name='payment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stripe_cater.PaymentOrder'),
        ),
    ]
