# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-08 22:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('business_site', '0006_auto_20161206_1211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basicinfo',
            name='logo',
            field=models.FileField(null=True, upload_to='media/photos'),
        ),
        migrations.AlterField(
            model_name='links',
            name='facebookpage',
            field=models.URLField(default='facebook.com'),
        ),
        migrations.AlterField(
            model_name='links',
            name='instagram',
            field=models.URLField(default='instagram.com'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.FileField(upload_to='media/photos'),
        ),
    ]
