# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-12 16:24
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('base', '0011_auto_20161112_0322'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='tax',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='confirmemailorder',
            name='create_at',
            field=models.DateTimeField(default=datetime.datetime(2016, 11, 12, 16, 24, 36, 96680)),
        ),
        migrations.AlterField(
            model_name='confirmemailorder',
            name='expire_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 11, 12, 16, 24, 36, 96610)),
        ),
        migrations.AlterField(
            model_name='order',
            name='create_at',
            field=models.DateField(default=datetime.datetime(2016, 11, 12, 16, 24, 36, 95014)),
        ),
        migrations.AlterField(
            model_name='order',
            name='due_date',
            field=models.DateField(default=datetime.datetime(2016, 11, 12, 16, 24, 36, 95144)),
        ),
    ]
