# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-30 20:59
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):
    dependencies = [
        ('stripe_cater', '0002_stripesubscripcion'),
    ]

    operations = [
        migrations.CreateModel(
            name='StripeInvoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripeid', models.CharField(max_length=50)),
                ('paid', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField()),
            ],
        ),
        migrations.AddField(
            model_name='stripesubscripcion',
            name='current_period_end',
            field=models.DateTimeField(default=datetime.datetime(2016, 11, 30, 20, 59, 34, 900970, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stripesubscripcion',
            name='current_period_start',
            field=models.DateTimeField(default=datetime.datetime(2016, 11, 30, 20, 59, 41, 885226, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stripeinvoice',
            name='subscription',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stripe_cater.StripeSubscripcion'),
        ),
    ]
