# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-06 12:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('business_site', '0005_basicinfo_website'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebDomain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=50)),
                ('website', models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE,
                                                 to='business_site.Website')),
            ],
        ),
        migrations.RemoveField(
            model_name='gallery',
            name='background',
        ),
        migrations.AddField(
            model_name='photo',
            name='asbackground',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='basicinfo',
            name='logo',
            field=models.ImageField(blank=True, upload_to='/home/maykel/PycharmProjects/caterfull/media/photos'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(blank=True, upload_to='/home/maykel/PycharmProjects/caterfull/media/photos'),
        ),
    ]
