# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-02 04:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('stripe_cater', '0008_auto_20161202_0435'),
    ]

    operations = [
        migrations.RenameField(
            model_name='charge',
            old_name='description',
            new_name='destination',
        ),
    ]
