# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-09 15:02
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('base', '0003_auto_20161108_1911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='prefix',
            field=models.CharField(blank=True,
                                   choices=[('Sr', 'Sr'), ('Mr', 'Mr'), ('Mrs', 'Mrs'), ('Mss', 'Mss'), ('Ms', 'Ms')],
                                   max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='suffix',
            field=models.CharField(blank=True, choices=[('Jr', 'Jr')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='create_at',
            field=models.DateField(default=datetime.datetime(2016, 11, 9, 15, 2, 34, 403173)),
        ),
        migrations.AlterField(
            model_name='order',
            name='due_date',
            field=models.DateField(default=datetime.datetime(2016, 11, 9, 15, 2, 34, 403213)),
        ),
    ]
