# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-25 20:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('base', '0023_auto_20161125_2026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposal',
            name='client_message',
            field=models.TextField(default='', max_length=150, null=True),
        ),
    ]
