# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-09 15:39
from __future__ import unicode_literals

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('base', '0004_auto_20161109_1502'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.EmailField(max_length=254, unique=True, validators=[django.core.validators.EmailValidator()]),
        ),
        migrations.AlterField(
            model_name='customer',
            name='prefix',
            field=models.CharField(blank=True,
                                   choices=[('Sir', 'Sir'), ('Mr', 'Mr'), ('Mrs', 'Mrs'), ('Mss', 'Mss'), ('Ms', 'Ms')],
                                   max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='create_at',
            field=models.DateField(default=datetime.datetime(2016, 11, 9, 15, 39, 37, 444133)),
        ),
        migrations.AlterField(
            model_name='order',
            name='due_date',
            field=models.DateField(default=datetime.datetime(2016, 11, 9, 15, 39, 37, 444169)),
        ),
    ]
