# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-10 21:11
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('base', '0006_auto_20161110_2023'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='current',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='create_at',
            field=models.DateField(default=datetime.datetime(2016, 11, 10, 21, 11, 19, 286309)),
        ),
        migrations.AlterField(
            model_name='order',
            name='due_date',
            field=models.DateField(default=datetime.datetime(2016, 11, 10, 21, 11, 19, 286343)),
        ),
    ]
