# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-12 21:42
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('base', '0014_auto_20161112_2141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='confirmemailorder',
            name='create_at',
            field=models.DateTimeField(default=datetime.datetime(2016, 11, 12, 21, 42, 57, 418192)),
        ),
        migrations.AlterField(
            model_name='confirmemailorder',
            name='expire_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 11, 12, 21, 42, 57, 418120)),
        ),
        migrations.AlterField(
            model_name='order',
            name='create_at',
            field=models.DateField(default=datetime.datetime(2016, 11, 12, 21, 42, 57, 416207)),
        ),
        migrations.AlterField(
            model_name='order',
            name='due_date',
            field=models.DateField(default=datetime.datetime(2016, 11, 12, 21, 42, 57, 416326)),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='business',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions',
                                    to='base.Business'),
        ),
    ]
