# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-13 03:14
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ('base', '0015_auto_20161112_2142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='confirmemailorder',
            name='create_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='confirmemailorder',
            name='expire_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='order',
            name='create_at',
            field=models.DateField(default=datetime.datetime(2016, 11, 13, 3, 14, 2, 851503)),
        ),
        migrations.AlterField(
            model_name='order',
            name='due_date',
            field=models.DateField(default=datetime.datetime(2016, 11, 13, 3, 14, 2, 851638)),
        ),
    ]
