# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-14 15:44
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('base', '0019_auto_20161113_1626'),
    ]

    operations = [
        migrations.CreateModel(
            name='N_Proposal_Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
            ],
        ),
        migrations.AlterField(
            model_name='order',
            name='create_at',
            field=models.DateField(default=datetime.datetime(2016, 11, 14, 15, 44, 55, 308839)),
        ),
        migrations.AlterField(
            model_name='order',
            name='due_date',
            field=models.DateField(default=datetime.datetime(2016, 11, 14, 15, 44, 55, 308875)),
        ),
    ]
