# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-08 22:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('base', '0028_auto_20161205_1946'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='logo',
            field=models.FileField(null=True, upload_to='profile'),
        ),
    ]
