# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-30 19:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('stripe_cater', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StripeSubscripcion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripeid', models.CharField(max_length=50)),
                ('stripestatus', models.CharField(max_length=50)),
                ('current', models.BooleanField(default=True)),
                ('stripecustomer',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions',
                                   to='stripe_cater.StripeCustomer')),
            ],
        ),
    ]
